### ISSUE TITLE
sensitive_data.md: ETS data written to the crash dump?

### ISSUE THREAD

**Issue by tanguilp** [erlef/security-wg#11]
I have no real life experience with introspecting crash dumps, but I can find no mention of ETS table being dump to the crash dump file (as referred in the "ETS tables" section of the `sensitive_data.md` file).

According to [this documentation](http://erlang.org/doc/apps/erts/crash_dump.html#ets-tables) only tables metadata are written to crash dumps.

**Comment by voltone** [comment]
Right, good catch. Will fix. Thanks!
