### ISSUE TITLE
ssl: match_fun example is not supported in mix releases

### ISSUE THREAD

**Issue by bernardo-martinez** [erlef/security-wg#27]
Hey, 

Just to inform you that the elixir examples provided in the [ssl section](https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/ssl.html):
```
match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
```

are not valid in mix releases given that releases [do not accept anonymous functions](https://elixirforum.com/t/mix-do-compile-release-could-not-read-configuration-file-config-runtime-exs-not-found/37800/3?u=bernardo).

When building the release it results in the following error:
```
** (Mix) Could not read configuration file. It has invalid configuration terms such as functions, references, and pids. Please make sure your configuration is made of numbers, atoms, strings, maps, tuples and lists. The following entries are wrong:
```

Thanks for the useful guide!

**Comment by voltone** [comment]
Correct, the code snippets given here were not intended to be used in config files.

If you wish to move some parts of the `:ssl` connect configuration options to configuration, I would recommend you only move those things that might change (e.g. `:ciphers` and `:versions`). When you call `:ssl.connect` you then merge those options with the hardcoded defaults (e.g. `:match_fun`).
