### ISSUE TITLE
GitHub Team for ErlEF Security WG

### ISSUE THREAD

**Issue by maennchen** [erlef/security-wg#39]
## Purpose

We've started work on various repositories. To simplify permission management for repositories & members, I'd like to introduce some teams.

## Team Structure

I propose the following structure:

https://github.com/orgs/erlef/teams

* Security WG
  * _Repositories_
    * https://github.com/erlef/security-wg (Maintain)
  * _Members_
    * @voltone 
    * @max-au
    * @houllette
    * @peerst
    * @varnerac
    * @realcorvus
    * @maennchen 
  * _Team visibility_: Visible
  * _Child Teams_
    * Admin
      * _Repositories_
        * https://github.com/erlef/security-wg (Admin)
      * _Members_
        * @voltone 
      * _Team visibility_: Visible
    * OpenID
      * _Repositories_
        * https://github.com/erlef/oidcc (Maintain)
        * https://github.com/erlef/oidcc_plug (Maintain)
        * https://github.com/erlef/oidcc_cowboy (Maintain)
        * https://github.com/erlef/phx_gen_oidcc (Maintain)
        * https://github.com/erlef/oidcc_conformance (To be created; Maintain)
      * _Members_
        * @paulswartz
        * @maennchen 
      * _Team visibility_: Visible
      * _Child Teams_
        * Admin
          * _Repositories_
            * https://github.com/erlef/oidcc (Admin)
            * https://github.com/erlef/oidcc_plug (Admin)
            * https://github.com/erlef/oidcc_cowboy (Admin)
            * https://github.com/erlef/phx_gen_oidcc (Admin)
            * https://github.com/erlef/oidcc_conformance (To be created; Admin)
          * _Members_
            * @maennchen 
          * _Team visibility_: Visible

**Comment by max-au** [comment]
FYI, there are two Peers in the member list, I think we only need one, which is @peerst.

**Comment by maennchen** [comment]
@max-au Oops, corrected in the description

**Comment by max-au** [comment]
This structure is not supported by GitHub, one cannot have _Secret_ nested groups. We can make admin teams `Visible`, which I believe is better for transparency anyway.

**Comment by maennchen** [comment]
@max-au Works for me :+1:

**Comment by max-au** [comment]
This has been done, with some caveats:
* GitHub cannot have nested teams secret. So Admin teams are set to Visible. Which is great, we do want transparency
* GitHub does not support multiple teams with the same name, hence Security WG Admins are named `security-admin`, and OpenID admins are `security-openid-admin`.
